name: piggylicious
favicon: null
layout_spectrum: 1
typography_spectrum: 0.60833
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 1
  lightness: 0.6719310046173632
  saturation: 0.75
  rhythmicContrast: 0.9743736926466227
purpose: []
